// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracker.Data;

#nullable disable

namespace TimeTracker.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241021152112_PeerReview_PeerReviewQuestion_PeerReviewAnswer")]
    partial class PeerReview_PeerReviewQuestion_PeerReviewAnswer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TimeTracker.Models.PeerReview", b =>
                {
                    b.Property<int>("PeerReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PeerReviewId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RevieweeId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PeerReviewId");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("PeerReviews");
                });

            modelBuilder.Entity("TimeTracker.Models.PeerReviewAnswer", b =>
                {
                    b.Property<int>("PeerReviewAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PeerReviewAnswerId"));

                    b.Property<int>("NumericalFeedback")
                        .HasColumnType("int");

                    b.Property<int>("PeerReviewId")
                        .HasColumnType("int");

                    b.Property<int>("PeerReviewQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("WrittenFeedback")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PeerReviewAnswerId");

                    b.HasIndex("PeerReviewId");

                    b.HasIndex("PeerReviewQuestionId");

                    b.ToTable("PeerReviewAnswers");
                });

            modelBuilder.Entity("TimeTracker.Models.PeerReviewQuestion", b =>
                {
                    b.Property<int>("PeerReviewQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PeerReviewQuestionId"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PeerReviewQuestionId");

                    b.ToTable("PeerReviewQuestions");
                });

            modelBuilder.Entity("TimeTracker.Models.TimeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TimeLogs");
                });

            modelBuilder.Entity("TimeTracker.Models.TimeLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TimeLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeLogId");

                    b.ToTable("TimeLogEntries");
                });

            modelBuilder.Entity("TimeTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefaultPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NetID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NetID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TimeTracker.Models.PeerReview", b =>
                {
                    b.HasOne("TimeTracker.Models.User", "Reviewee")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeTracker.Models.User", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("TimeTracker.Models.PeerReviewAnswer", b =>
                {
                    b.HasOne("TimeTracker.Models.PeerReview", "PeerReview")
                        .WithMany("PeerReviewAnswers")
                        .HasForeignKey("PeerReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTracker.Models.PeerReviewQuestion", "PeerReviewQuestion")
                        .WithMany()
                        .HasForeignKey("PeerReviewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerReview");

                    b.Navigation("PeerReviewQuestion");
                });

            modelBuilder.Entity("TimeTracker.Models.TimeLog", b =>
                {
                    b.HasOne("TimeTracker.Models.User", "User")
                        .WithMany("TimeLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Models.TimeLogEntry", b =>
                {
                    b.HasOne("TimeTracker.Models.TimeLog", "TimeLog")
                        .WithMany("TimeLogEntries")
                        .HasForeignKey("TimeLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeLog");
                });

            modelBuilder.Entity("TimeTracker.Models.PeerReview", b =>
                {
                    b.Navigation("PeerReviewAnswers");
                });

            modelBuilder.Entity("TimeTracker.Models.TimeLog", b =>
                {
                    b.Navigation("TimeLogEntries");
                });

            modelBuilder.Entity("TimeTracker.Models.User", b =>
                {
                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("TimeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
